[package]
name = "mpcrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
optimization_engine = "0.7.4"
nalgebra = "0.30.1"
approx = "0.5.1"
